//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkContable.Models.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class REG_DET_PRESUPUESTOS
    {
        public long ID { get; set; }
        public int PRE_ID { get; set; }
        public int TRA_ID { get; set; }
    
        public virtual PRESUPUESTO PRESUPUESTO { get; set; }
        public virtual TRANSACCION TRANSACCION { get; set; }
    }
}
