//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkContable.Models.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class REG_DET_LIBROS
    {
        public int ID { get; set; }
        public Nullable<int> TRA_ID { get; set; }
        public int LIB_ID { get; set; }
    
        public virtual LIBRO_CONTABLE LIBRO_CONTABLE { get; set; }
        public virtual TRANSACCION TRANSACCION { get; set; }
    }
}
