//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkContable.Models.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANSACCION()
        {
            this.REG_DET_LIBROS = new HashSet<REG_DET_LIBROS>();
            this.REG_DET_PRESUPUESTOS = new HashSet<REG_DET_PRESUPUESTOS>();
        }
    
        public int ID { get; set; }
        public int RUB_ID { get; set; }
        public decimal TIPO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public Nullable<decimal> IMPUESTO { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REG_DET_LIBROS> REG_DET_LIBROS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REG_DET_PRESUPUESTOS> REG_DET_PRESUPUESTOS { get; set; }
        public virtual RUBRO RUBRO { get; set; }
    }
}
